services:

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']
            public: true

    Gingdev\Facebook\Command\:
        resource: ../../Command
